CC = gcc

compile:
	sudo $(CC) main.c \
	../helpers/helperCommand.c \
	-o /usr/bin/zylearn

	$(CC) main.c \
	../helpers/helperCommand.c \
	-o zylearn/usr/bin/zylearn

clear:
	sudo rm -rf /usr/bin/zylearn
	rm -rf /usr/bin/zylearn