#!/bin/sh
set -e

for dir in \
    /etc/skel/.config \
    /etc/skel/.fonts \
    /etc/skel/.icons \
    /etc/skel/.themes \
    /etc/skel/Desktop \
    /usr/share/images/desktop-base
do
    if [ -e "$dir" ]; then
        chown -R root:root "$dir"

        # Directories: readable and accessible
        find "$dir" -type d -exec chmod 755 {} \;

        # Files: readable, without unnecessary execute permissions
        find "$dir" -type f -exec chmod 644 {} \;
    fi
done

exit 0
