#!/bin/sh
set -e

# Write Zyphor identity file
cat > /usr/lib/os-release << 'EOF'
PRETTY_NAME="Zyphor OS v1.13.0-u19"
NAME="Zyphor OS GNU/Linux"
VERSION_ID="1.13.0"
VERSION="1.13.0"
VERSION_CODENAME=zyphor-os
ID=zyphor-os
ID_LIKE=debian
HOME_URL="https://www.facebook.com/profile.php?id=61573426796629"
SUPPORT_URL="https://www.facebook.com/mark.jason.penote.espelita"
BUG_REPORT_URL="https://m.me/100009131763374"
EOF

chmod 644 /usr/lib/os-release

# Create /etc/os-release symlink safely
if [ -e /etc/os-release ] && [ ! -L /etc/os-release ]; then
    mv /etc/os-release /etc/os-release.bak
fi

ln -sf /usr/lib/os-release /etc/os-release

exit 0