#!/bin/sh
set -e

cat > /etc/apt/sources.list.d/zyphor.list <<EOF
deb [trusted=yes] https://zyphor-os.github.io stable main
EOF

chown root:root /etc/apt/sources.list.d/zyphor.list
chmod 644 /etc/apt/sources.list.d/zyphor.list

apt update

exit 0