#!/bin/sh
set -e

# Set ownership

chown -R root:root /usr/share/zyphor-command-center
chown root:root /usr/local/bin/zyphor-command-center
chown root:root /usr/share/applications/zyphor-command-center.desktop

# Set file permissions

find /usr/share/zyphor-command-center -type f -exec chmod 555 {} +

# Executable file

chmod 555 /usr/local/bin/zyphor-command-center

# Desktop entry

chmod 555 /usr/share/applications/zyphor-command-center.desktop

exit 0