#!/bin/sh
set -e

cat > /etc/apt/sources.list.d/zyphor.list <<EOF
deb [arch=amd64 trusted=yes] https://zyphor-os.github.io/v2-ada-lovelace stable main
EOF

chown root:root /etc/apt/sources.list.d/zyphor.list
chmod 644 /etc/apt/sources.list.d/zyphor.list

apt update

exit 0